# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y libasound2-dev
      # specify any bash command here prefixed with `run: `
      - run: chmod +x scripts/coverage.sh
      - run: make test-ci
      - run: bash <(curl -s https://codecov.io/bash)
